name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  injectable: ^2.5.0
  otp: ^3.1.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/login_page/
